version: '2'
services:
    mytestapplication-app:
        image: mytestapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mytestapplication-mysql:3306/mytestapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mytestapplication-mysql:
        extends:
            file: mysql.yml
            service: mytestapplication-mysql
